from typing import List
from langchain_ollama import ChatOllama
from langchain_ollama import OllamaEmbeddings
from langchain_core.output_parsers import StrOutputParser
from sklearn.metrics.pairwise import cosine_similarity
from pathlib import Path

# Relative import if we run this script directly this will give error
# Import evaluate.py or Evaluate class from it outside the package, it will work
# . here means current package or folder, .. means parent folder level
from .eval_prompts import prompt_t_faithfulness
from .eval_prompts import prompt_t_factual_correctnes
from .eval_prompts import prompt_t_answer_relevance
from .eval_prompts import prompt_t_context_relevance
from .schema_classes import IntScore

class Evaluate:
    def __init__(self,
                 questions:List[str], contexts:List[str], answers:List[str], ground_truths:List[str]):
        """Creates object of Evaluate class, and initializes the test dataset.
        Args:
            question: List of question strings
            contexts: List of context strings
            answers: List of answer strings (Thes are the answers generated by model)
            ground_truths: List of ground truths from the corresponding contexts
        Returns:
            dataset: Dataset object.
        """
        self.answers = answers
        self.contexts = contexts
        self.questions = questions
        self.ground_truths = ground_truths

        len_a = len(self.answers)
        len_c = len(self.contexts)
        len_q = len(self.questions)
        len_gt = len(self.ground_truths)

        lengths = {
            'answers':len_a,
            'contexts':len_c,
            'questions':len_q,
            'ground_truths':len_gt
        }
        if len(set(lengths.values())) != 1:
            raise ValueError(f"Length mismatch: {lengths}")

    def faithfulness(self, model:ChatOllama) -> dict:
        """Calculates faithfulness.
        Args:
            model: Langchain's chat model
        Returns:
            score_total(dict): Dictionary containing the total aggregated faitfulness score and individual score values for each sample of the data.
        """

        print("-> Calculating faitfulness")
        struct_model = model.with_structured_output(IntScore)
        chain = prompt_t_faithfulness | struct_model

        scores = []
        for i in range(len(self.questions)):
            res = chain.invoke({'context':self.contexts[i], 'answer':self.answers[i]})
            # print(res.score)
            scores.append(res.score)
        scores = [(score/2) for score in scores] # normalize - to get values between [0,1]
        score_total = sum(scores) / len(scores) # average of the individual scores
        score_dict = {'total_score':score_total, 'individual_scores':scores}
        return score_dict
    
    def factual_correctness(self, model:ChatOllama) -> dict:
        """Calculates factual correctness.
        Args:
            model: Langchain's chat model
        Returns:
            score_total(dict): Dictionary containing the total aggregated factual correctness score and individual score values for each sample of the data.
        """
        print("-> Calculating factual correctness")
        struct_model = model.with_structured_output(IntScore)
        chain = prompt_t_factual_correctnes | struct_model

        scores = []
        for i in range(len(self.ground_truths)):
            res = chain.invoke({'ground_truth':self.ground_truths[i], 'answer':self.answers[i]})
            scores.append(res.score)
            # print(res.score)
        scores = [(score/2) for score in scores]
        score_total = sum(scores) / len(scores)
        score_dict = {'total_score':score_total, 'individual_scores':scores}

        return score_dict
    
    def answer_relevance_score(self, embed_model:OllamaEmbeddings, question:str, question_llm:str) -> float:
        """
        Calculates answer relevance score for a single pair of original question and question created by LLM.
        Args:
            question(str): The original question
            question_llm(str): The question generated by llm with the help of it's own generated answer
        Returns:
            score(float): answer relevance score
        """

        vectors = embed_model.embed_documents(
            texts=[question, question_llm]
        )
        score = cosine_similarity(X=[vectors[0]], Y=[vectors[1]])
        score = score[0][0]
        if score >= 0.6:
            return 1.0
        elif score < 0.6 and score >= 0.5:
            return 0.5
        
        return 0.0
    

    def answer_relevance(self, model:ChatOllama, embed_model:OllamaEmbeddings) -> dict:
        """Calculates answer relevance.
        Args:
            model: Langchain's chat model
        Returns:
            score_dict(dict): Dictionary containing the total aggregated answer relevance score and individual score values for each sample of the data.
        """
        print("-> Calculating answer relevance")
        chain = prompt_t_answer_relevance | model | StrOutputParser()
        scores = []
        question_llm = []
        for i in range(len(self.questions)):
            que_llm = chain.invoke({'answer':self.answers[i]})
            question_llm.append(que_llm)
        for i in range(len(self.questions)):
            score = self.answer_relevance_score(
                embed_model=embed_model,
                question=self.questions[i],
                question_llm=question_llm[i]
            )
            scores.append(score)

        score_total = sum(scores) / len(scores)
        score_dict = {'total_score':score_total, 'individual_scores':scores}
        return score_dict

    def context_relevance(self, model:ChatOllama):
        """
        Calculates context relevance.
        Args:
            model: Langchain's chat model
        Returns:
            score_total(dict): Dictionary containing the total aggregated factual correctness score and individual score values for each sample of the data.
        """
        print("-> Calculating context relevance")
        struct_model = model.with_structured_output(IntScore)
        chain = prompt_t_context_relevance | struct_model
        scores = []
        for i in range(len(self.questions)):
            res = chain.invoke({'question':self.questions[i], 'context':self.contexts[i]})
            # print(res.score)
            scores.append(res.score)

        scores = [(score/2) for score in scores]
        score_total = sum(scores) / len(scores)
        score_dict = {'total_score':score_total, 'individual_scores':scores}

        return score_dict

if __name__ == "__main__":
    print("Runs succesfully!")


